config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "game#index"
  namespace :game do
    post "play", :play
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_controller.rb
class GameController < ApplicationController
	layout 'application'
	def index
	end

	def create
	end

	def play
		player_choice = params[:choice].to_sym
		@curb_choice = Curb.choice.to_sym || Game.random_throw
		@player_message, @curb_message = case Game.decide_winner(player_choice, @curb_choice)
		when :draw
			["You drew!", "Curb with #{@curb_choice} drew"]
		when :player1
			["You won!", "Curb with #{@curb_choice} lost"]
		when :player2
			["You lost!", "Curb with #{@curb_choice} won"]
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/game/index.html.erb
<h1>Rock - Paper - Scissors</h1>
<p style="font-size: 21px; text-align: center; width: 500px; margin: 10px auto; display: block;">Rock Paper Scissors is a zero sum game that is usually played by two people using their hands and no tools. The idea is to make shapes with an outstretched hand where each shape will have a certain degree of power and will lead to an outcome.</p>
<h2>Select your bet</h2>

<%= turbo_frame_tag :game do %>
	<% Game::THROWS.each do |t| %>
		<%= button_to(game_play_path, remote: true, form: { style: "display: inline-block" }, params: {choice: t}, style: "display: inline-block") do %>
			<%= image_tag "game/#{t}.svg", style: "width: 80px; height: 175px;" %>
		<% end %>
	<% end %>
<% end %>

app/views/game/play.html.erb
<%= turbo_frame_tag :game do %>
	<h1 style="font-size: 21px"><%= @player_message %></h1>
	<p><%= @curb_message %></p>
	<%= image_tag "game/#{@curb_choice}.svg", style: "width: 80px" %>
	<%= link_to 'Play again', root_path, 'data-turbo-frame': '_top', style: "display: block" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welcome to Rock, Paper, Scissors!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="text-align: center;">
    <%= yield %>
  </body>
</html>